# Generated by Django 4.2.15 on 2025-01-02 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
