# Generated by Django 5.1.3 on 2025-03-25 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_comment_delete_category_delete_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
